name: Deploy Next.js site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  deployments: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
        
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
            
      - name: Cache Build Output
        uses: actions/cache@v4
        with:
          path: |
           .next/cache
          key: ${{ runner.os }}-nextjs-build-output-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-build-output-
            
      - name: Build
        run: npm run build # Assuming you have a build script defined in your package.json
        
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: nextjs-build
      #     path: .next/
          
      # - name: Archive artifact
      #   run: tar czf nextjs-build.tar.gz.next/

      # - name: Upload archived artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: nextjs-archive
      #     path: nextjs-build.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .next
