name: Deploy Next.js site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          
      # - name: Install pnpm
        # run: npm install -g pnpm
        
      - name: Install Dependencies
        run: npm install
        
      - name: Build with Next.js
        run: npm run build
        
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

              - name: Cache Build Output
              uses: actions/cache@v4
              with:
                path: |
                 .next/cache
                key: ${{ runner.os }}-nextjs-build-output-${{ hashFiles('**/pnpm-lock.yaml') }}
                restore-keys: |
                  ${{ runner.os }}-nextjs-build-output-
            
            
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build
          path: .next/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: nextjs-build
          path: .
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./next/.next
          publish_branch: master # Change this to master if using the master branch for GitHub Pages
          allow_empty_commit: false
          keep_files: false
          force_orphan: false
          enable_jekyll: false
          disable_nojekyll: false
          exclude_assets: .github
